---
- name: cofigure a basic server
  hosts: webservers
  become: true
  tasks: 
    - name: ensure that httpd package is present
      yum:
         name: httpd
         state: present
    - name: start and enable the httpd service
      service:
         name: httpd
         state: started
         enabled: true
    - name: allow port 80/tcp is the firewall
      firewalld:
         port: 80/tcp
         permanent: true
         immediate: true
         state: enabled
    - name: deploy the inmdex.html from index.html.j2
      template:
         src: index.html.j2
         dest: /var/www/html/index.html
